export const mappingConfig = {
  smplRoleMapping: {
    'SMPL Salesperson': 'project_management',
    'SMPL General Manager': 'project_management',
    'SMPL Order Processor': 'labor_coordinator',
    'SMPL Sales-Requested Personnel Coordinator': 'labor_coordinator',
  },
  marketAirportFallback: {
    'DALLAS': 'DFW',
    'DALLAS/FT-WORTH': 'DFW',
    'FT-WORTH': 'DFW',
    'FORT WORTH': 'DFW',
    'NEW YORK': 'JFK',
    'LOS ANGELES': 'LAX',
    'CHICAGO': 'ORD',
    'HOUSTON': 'IAH',
    'ATLANTA': 'ATL',
    'MIAMI': 'MIA',
    'LAS VEGAS': 'LAS',
    'ORLANDO': 'MCO',
    'PHOENIX': 'PHX',
    'SEATTLE': 'SEA',
    'DENVER': 'DEN',
    'BOSTON': 'BOS',
    'SAN FRANCISCO': 'SFO',
    'WASHINGTON': 'DCA',
    'NASHVILLE': 'BNA',
    'MINNEAPOLIS': 'MSP',
    'DETROIT': 'DTW',
    'CHARLOTTE': 'CLT',
    'MEMPHIS': 'MEM',
    'NEW ORLEANS': 'MSY',
    'KANSAS CITY': 'MCI',
    'SAN ANTONIO': 'SAT',
    'AUSTIN': 'AUS',
    'SAN DIEGO': 'SAN',
    'PORTLAND': 'PDX',
    'SALT LAKE CITY': 'SLC',
    'INDIANAPOLIS': 'IND',
    'COLUMBUS': 'CMH',
    'RALEIGH': 'RDU',
    'PITTSBURGH': 'PIT',
    'CINCINNATI': 'CVG',
    'CLEVELAND': 'CLE',
    'TAMPA': 'TPA',
    'ST. LOUIS': 'STL',
  } as Record<string, string>,
  rateSettingDefault: 'crew_default',
  eventStatusMapping: {
    'Confirmed': 'confirmed',
    'Unconfirmed': 'unconfirmed',
    'Tentative': 'tentative',
    'Canceled': 'canceled',
    'Cancelled': 'canceled',
    'Hold': 'hold',
    'Prospect': 'prospect',
  } as Record<string, string>,
}
